spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/expensify
    username: expensify_admin
    password: <YOUR_PASSWORD_HERE>
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
